### ISSUE TITLE
Check server available for connection

### ISSUE THREAD

**Issue by stkraine** [EECE3093C/team_orange_keylogger#9]
### Objective
The objective of this task is to make sure the web server is available to send data to
### Deliverables
Code that can pinf the web server will be the deliverable

**Comment by daniel-corcoran** [comment]
Might be difficult to have it done this iteration since I don't intend to have the web server online until next iteration

**Comment by stkraine** [comment]
gotcha, gonna move it to iteration 4 then.

**Comment by stkraine** [comment]
pinging the server appears to work from CLI, need to implement in code. can ping here:
team-orange-webserver-ulfju27txa-ue.a.run.app/](https://team-orange-webserver-ulfju27txa-ue.a.run.app

**Comment by stkraine** [comment]
ping works from the keylogger!
